// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirPollution.proto

package service.airpollution;

public interface CityReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airpollution.CityReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
