// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirPollution.proto

package service.airpollution;

public interface CityLevelReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airpollution.CityLevelReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string AirPollutionLevel = 2;</code>
   */
  java.lang.String getAirPollutionLevel();
  /**
   * <code>string AirPollutionLevel = 2;</code>
   */
  com.google.protobuf.ByteString
      getAirPollutionLevelBytes();
}
