// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirPollution.proto

package service.airpollution;

public interface LevelReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airpollution.LevelReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string AirPollutionLevel = 1;</code>
   */
  java.lang.String getAirPollutionLevel();
  /**
   * <code>string AirPollutionLevel = 1;</code>
   */
  com.google.protobuf.ByteString
      getAirPollutionLevelBytes();
}
