// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirPollution.proto

package service.airpollution;

public interface MonthRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:airpollution.MonthRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string AirPollutionMonth = 1;</code>
   */
  java.lang.String getAirPollutionMonth();
  /**
   * <code>string AirPollutionMonth = 1;</code>
   */
  com.google.protobuf.ByteString
      getAirPollutionMonthBytes();
}
