// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WaterPollution.proto

package service.waterpollution;

public interface CityLevelReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterpollution.CityLevelReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string WaterPollutionLevel = 2;</code>
   */
  java.lang.String getWaterPollutionLevel();
  /**
   * <code>string WaterPollutionLevel = 2;</code>
   */
  com.google.protobuf.ByteString
      getWaterPollutionLevelBytes();
}
