// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WaterPollution.proto

package service.waterpollution;

public interface CityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterpollution.CityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
