// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WaterPollution.proto

package service.waterpollution;

public interface LevelReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterpollution.LevelReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string WaterPollutionLevel = 1;</code>
   */
  java.lang.String getWaterPollutionLevel();
  /**
   * <code>string WaterPollutionLevel = 1;</code>
   */
  com.google.protobuf.ByteString
      getWaterPollutionLevelBytes();
}
