// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WaterPollution.proto

package service.waterpollution;

public interface MonthRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:waterpollution.MonthRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string WaterPollutionMonth = 1;</code>
   */
  java.lang.String getWaterPollutionMonth();
  /**
   * <code>string WaterPollutionMonth = 1;</code>
   */
  com.google.protobuf.ByteString
      getWaterPollutionMonthBytes();
}
