// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WaterPollution.proto

package service.waterpollution;

public final class WaterPollutionServiceImpl {
  private WaterPollutionServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterpollution_CityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterpollution_CityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterpollution_LevelReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterpollution_LevelReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterpollution_LevelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterpollution_LevelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterpollution_CityReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterpollution_CityReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterpollution_MonthRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterpollution_MonthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_waterpollution_CityLevelReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_waterpollution_CityLevelReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024WaterPollution.proto\022\016waterpollution\"\037" +
      "\n\013CityRequest\022\020\n\010location\030\001 \001(\t\")\n\nLevel" +
      "Reply\022\033\n\023WaterPollutionLevel\030\001 \001(\t\"+\n\014Le" +
      "velRequest\022\033\n\023WaterPollutionLevel\030\001 \001(\t\"" +
      "\035\n\tCityReply\022\020\n\010location\030\001 \001(\t\"+\n\014MonthR" +
      "equest\022\033\n\023WaterPollutionMonth\030\001 \001(\t\"?\n\016C" +
      "ityLevelReply\022\020\n\010location\030\001 \001(\t\022\033\n\023Water" +
      "PollutionLevel\030\002 \001(\t2\214\002\n\016WaterPollution\022" +
      "O\n\022WaterPollutionCity\022\033.waterpollution.C" +
      "ityRequest\032\032.waterpollution.LevelReply\"\000" +
      "\022P\n\023WaterPollutionLevel\022\034.waterpollution" +
      ".LevelRequest\032\031.waterpollution.CityReply" +
      "\"\000\022W\n\023WaterPollutionMonth\022\034.waterpolluti" +
      "on.MonthRequest\032\036.waterpollution.CityLev" +
      "elReply\"\0000\001B5\n\026service.waterpollutionB\031W" +
      "aterPollutionServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_waterpollution_CityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_waterpollution_CityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterpollution_CityRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_waterpollution_LevelReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_waterpollution_LevelReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterpollution_LevelReply_descriptor,
        new java.lang.String[] { "WaterPollutionLevel", });
    internal_static_waterpollution_LevelRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_waterpollution_LevelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterpollution_LevelRequest_descriptor,
        new java.lang.String[] { "WaterPollutionLevel", });
    internal_static_waterpollution_CityReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_waterpollution_CityReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterpollution_CityReply_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_waterpollution_MonthRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_waterpollution_MonthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterpollution_MonthRequest_descriptor,
        new java.lang.String[] { "WaterPollutionMonth", });
    internal_static_waterpollution_CityLevelReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_waterpollution_CityLevelReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_waterpollution_CityLevelReply_descriptor,
        new java.lang.String[] { "Location", "WaterPollutionLevel", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
