// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentalPollution.proto

package service.environmentalpollution;

public interface DecideLocationReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:environmentalpollution.DecideLocationReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Grade = 1;</code>
   */
  java.lang.String getGrade();
  /**
   * <code>string Grade = 1;</code>
   */
  com.google.protobuf.ByteString
      getGradeBytes();
}
