// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentalPollution.proto

package service.environmentalpollution;

public interface DecideLocationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:environmentalpollution.DecideLocationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string Location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
