// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentalPollution.proto

package service.environmentalpollution;

public interface EnvironmentalEvaluationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:environmentalpollution.EnvironmentalEvaluationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string EnvironmentalPollutionLevel = 1;</code>
   */
  java.lang.String getEnvironmentalPollutionLevel();
  /**
   * <code>string EnvironmentalPollutionLevel = 1;</code>
   */
  com.google.protobuf.ByteString
      getEnvironmentalPollutionLevelBytes();
}
