// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentalPollution.proto

package service.environmentalpollution;

/**
 * Protobuf type {@code environmentalpollution.EnvironmentalEvaluationReply}
 */
public  final class EnvironmentalEvaluationReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:environmentalpollution.EnvironmentalEvaluationReply)
    EnvironmentalEvaluationReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EnvironmentalEvaluationReply.newBuilder() to construct.
  private EnvironmentalEvaluationReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EnvironmentalEvaluationReply() {
    grade_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EnvironmentalEvaluationReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            grade_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return service.environmentalpollution.EnvironmentalPollutionServiceImpl.internal_static_environmentalpollution_EnvironmentalEvaluationReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return service.environmentalpollution.EnvironmentalPollutionServiceImpl.internal_static_environmentalpollution_EnvironmentalEvaluationReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            service.environmentalpollution.EnvironmentalEvaluationReply.class, service.environmentalpollution.EnvironmentalEvaluationReply.Builder.class);
  }

  public static final int GRADE_FIELD_NUMBER = 1;
  private volatile java.lang.Object grade_;
  /**
   * <code>string Grade = 1;</code>
   */
  public java.lang.String getGrade() {
    java.lang.Object ref = grade_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      grade_ = s;
      return s;
    }
  }
  /**
   * <code>string Grade = 1;</code>
   */
  public com.google.protobuf.ByteString
      getGradeBytes() {
    java.lang.Object ref = grade_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      grade_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getGradeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, grade_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getGradeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, grade_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof service.environmentalpollution.EnvironmentalEvaluationReply)) {
      return super.equals(obj);
    }
    service.environmentalpollution.EnvironmentalEvaluationReply other = (service.environmentalpollution.EnvironmentalEvaluationReply) obj;

    boolean result = true;
    result = result && getGrade()
        .equals(other.getGrade());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GRADE_FIELD_NUMBER;
    hash = (53 * hash) + getGrade().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static service.environmentalpollution.EnvironmentalEvaluationReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(service.environmentalpollution.EnvironmentalEvaluationReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code environmentalpollution.EnvironmentalEvaluationReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:environmentalpollution.EnvironmentalEvaluationReply)
      service.environmentalpollution.EnvironmentalEvaluationReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return service.environmentalpollution.EnvironmentalPollutionServiceImpl.internal_static_environmentalpollution_EnvironmentalEvaluationReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return service.environmentalpollution.EnvironmentalPollutionServiceImpl.internal_static_environmentalpollution_EnvironmentalEvaluationReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              service.environmentalpollution.EnvironmentalEvaluationReply.class, service.environmentalpollution.EnvironmentalEvaluationReply.Builder.class);
    }

    // Construct using service.environmentalpollution.EnvironmentalEvaluationReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      grade_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return service.environmentalpollution.EnvironmentalPollutionServiceImpl.internal_static_environmentalpollution_EnvironmentalEvaluationReply_descriptor;
    }

    @java.lang.Override
    public service.environmentalpollution.EnvironmentalEvaluationReply getDefaultInstanceForType() {
      return service.environmentalpollution.EnvironmentalEvaluationReply.getDefaultInstance();
    }

    @java.lang.Override
    public service.environmentalpollution.EnvironmentalEvaluationReply build() {
      service.environmentalpollution.EnvironmentalEvaluationReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public service.environmentalpollution.EnvironmentalEvaluationReply buildPartial() {
      service.environmentalpollution.EnvironmentalEvaluationReply result = new service.environmentalpollution.EnvironmentalEvaluationReply(this);
      result.grade_ = grade_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof service.environmentalpollution.EnvironmentalEvaluationReply) {
        return mergeFrom((service.environmentalpollution.EnvironmentalEvaluationReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(service.environmentalpollution.EnvironmentalEvaluationReply other) {
      if (other == service.environmentalpollution.EnvironmentalEvaluationReply.getDefaultInstance()) return this;
      if (!other.getGrade().isEmpty()) {
        grade_ = other.grade_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      service.environmentalpollution.EnvironmentalEvaluationReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (service.environmentalpollution.EnvironmentalEvaluationReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object grade_ = "";
    /**
     * <code>string Grade = 1;</code>
     */
    public java.lang.String getGrade() {
      java.lang.Object ref = grade_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        grade_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Grade = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGradeBytes() {
      java.lang.Object ref = grade_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        grade_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Grade = 1;</code>
     */
    public Builder setGrade(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      grade_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Grade = 1;</code>
     */
    public Builder clearGrade() {
      
      grade_ = getDefaultInstance().getGrade();
      onChanged();
      return this;
    }
    /**
     * <code>string Grade = 1;</code>
     */
    public Builder setGradeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      grade_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:environmentalpollution.EnvironmentalEvaluationReply)
  }

  // @@protoc_insertion_point(class_scope:environmentalpollution.EnvironmentalEvaluationReply)
  private static final service.environmentalpollution.EnvironmentalEvaluationReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new service.environmentalpollution.EnvironmentalEvaluationReply();
  }

  public static service.environmentalpollution.EnvironmentalEvaluationReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EnvironmentalEvaluationReply>
      PARSER = new com.google.protobuf.AbstractParser<EnvironmentalEvaluationReply>() {
    @java.lang.Override
    public EnvironmentalEvaluationReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EnvironmentalEvaluationReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EnvironmentalEvaluationReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EnvironmentalEvaluationReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public service.environmentalpollution.EnvironmentalEvaluationReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

