// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentalPollution.proto

package service.environmentalpollution;

/**
 * <pre>
 * Define the messages
 * </pre>
 *
 * Protobuf type {@code environmentalpollution.EnvironmentalEvaluationRequest}
 */
public  final class EnvironmentalEvaluationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:environmentalpollution.EnvironmentalEvaluationRequest)
    EnvironmentalEvaluationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EnvironmentalEvaluationRequest.newBuilder() to construct.
  private EnvironmentalEvaluationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EnvironmentalEvaluationRequest() {
    environmentalPollutionLevel_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EnvironmentalEvaluationRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            environmentalPollutionLevel_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return service.environmentalpollution.EnvironmentalPollutionServiceImpl.internal_static_environmentalpollution_EnvironmentalEvaluationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return service.environmentalpollution.EnvironmentalPollutionServiceImpl.internal_static_environmentalpollution_EnvironmentalEvaluationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            service.environmentalpollution.EnvironmentalEvaluationRequest.class, service.environmentalpollution.EnvironmentalEvaluationRequest.Builder.class);
  }

  public static final int ENVIRONMENTALPOLLUTIONLEVEL_FIELD_NUMBER = 1;
  private volatile java.lang.Object environmentalPollutionLevel_;
  /**
   * <code>string EnvironmentalPollutionLevel = 1;</code>
   */
  public java.lang.String getEnvironmentalPollutionLevel() {
    java.lang.Object ref = environmentalPollutionLevel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      environmentalPollutionLevel_ = s;
      return s;
    }
  }
  /**
   * <code>string EnvironmentalPollutionLevel = 1;</code>
   */
  public com.google.protobuf.ByteString
      getEnvironmentalPollutionLevelBytes() {
    java.lang.Object ref = environmentalPollutionLevel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      environmentalPollutionLevel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEnvironmentalPollutionLevelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, environmentalPollutionLevel_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEnvironmentalPollutionLevelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, environmentalPollutionLevel_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof service.environmentalpollution.EnvironmentalEvaluationRequest)) {
      return super.equals(obj);
    }
    service.environmentalpollution.EnvironmentalEvaluationRequest other = (service.environmentalpollution.EnvironmentalEvaluationRequest) obj;

    boolean result = true;
    result = result && getEnvironmentalPollutionLevel()
        .equals(other.getEnvironmentalPollutionLevel());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENVIRONMENTALPOLLUTIONLEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getEnvironmentalPollutionLevel().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static service.environmentalpollution.EnvironmentalEvaluationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static service.environmentalpollution.EnvironmentalEvaluationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(service.environmentalpollution.EnvironmentalEvaluationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Define the messages
   * </pre>
   *
   * Protobuf type {@code environmentalpollution.EnvironmentalEvaluationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:environmentalpollution.EnvironmentalEvaluationRequest)
      service.environmentalpollution.EnvironmentalEvaluationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return service.environmentalpollution.EnvironmentalPollutionServiceImpl.internal_static_environmentalpollution_EnvironmentalEvaluationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return service.environmentalpollution.EnvironmentalPollutionServiceImpl.internal_static_environmentalpollution_EnvironmentalEvaluationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              service.environmentalpollution.EnvironmentalEvaluationRequest.class, service.environmentalpollution.EnvironmentalEvaluationRequest.Builder.class);
    }

    // Construct using service.environmentalpollution.EnvironmentalEvaluationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      environmentalPollutionLevel_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return service.environmentalpollution.EnvironmentalPollutionServiceImpl.internal_static_environmentalpollution_EnvironmentalEvaluationRequest_descriptor;
    }

    @java.lang.Override
    public service.environmentalpollution.EnvironmentalEvaluationRequest getDefaultInstanceForType() {
      return service.environmentalpollution.EnvironmentalEvaluationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public service.environmentalpollution.EnvironmentalEvaluationRequest build() {
      service.environmentalpollution.EnvironmentalEvaluationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public service.environmentalpollution.EnvironmentalEvaluationRequest buildPartial() {
      service.environmentalpollution.EnvironmentalEvaluationRequest result = new service.environmentalpollution.EnvironmentalEvaluationRequest(this);
      result.environmentalPollutionLevel_ = environmentalPollutionLevel_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof service.environmentalpollution.EnvironmentalEvaluationRequest) {
        return mergeFrom((service.environmentalpollution.EnvironmentalEvaluationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(service.environmentalpollution.EnvironmentalEvaluationRequest other) {
      if (other == service.environmentalpollution.EnvironmentalEvaluationRequest.getDefaultInstance()) return this;
      if (!other.getEnvironmentalPollutionLevel().isEmpty()) {
        environmentalPollutionLevel_ = other.environmentalPollutionLevel_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      service.environmentalpollution.EnvironmentalEvaluationRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (service.environmentalpollution.EnvironmentalEvaluationRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object environmentalPollutionLevel_ = "";
    /**
     * <code>string EnvironmentalPollutionLevel = 1;</code>
     */
    public java.lang.String getEnvironmentalPollutionLevel() {
      java.lang.Object ref = environmentalPollutionLevel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        environmentalPollutionLevel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string EnvironmentalPollutionLevel = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEnvironmentalPollutionLevelBytes() {
      java.lang.Object ref = environmentalPollutionLevel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        environmentalPollutionLevel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string EnvironmentalPollutionLevel = 1;</code>
     */
    public Builder setEnvironmentalPollutionLevel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      environmentalPollutionLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string EnvironmentalPollutionLevel = 1;</code>
     */
    public Builder clearEnvironmentalPollutionLevel() {
      
      environmentalPollutionLevel_ = getDefaultInstance().getEnvironmentalPollutionLevel();
      onChanged();
      return this;
    }
    /**
     * <code>string EnvironmentalPollutionLevel = 1;</code>
     */
    public Builder setEnvironmentalPollutionLevelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      environmentalPollutionLevel_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:environmentalpollution.EnvironmentalEvaluationRequest)
  }

  // @@protoc_insertion_point(class_scope:environmentalpollution.EnvironmentalEvaluationRequest)
  private static final service.environmentalpollution.EnvironmentalEvaluationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new service.environmentalpollution.EnvironmentalEvaluationRequest();
  }

  public static service.environmentalpollution.EnvironmentalEvaluationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EnvironmentalEvaluationRequest>
      PARSER = new com.google.protobuf.AbstractParser<EnvironmentalEvaluationRequest>() {
    @java.lang.Override
    public EnvironmentalEvaluationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EnvironmentalEvaluationRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EnvironmentalEvaluationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EnvironmentalEvaluationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public service.environmentalpollution.EnvironmentalEvaluationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

