// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentalPollution.proto

package service.environmentalpollution;

public final class EnvironmentalPollutionServiceImpl {
  private EnvironmentalPollutionServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environmentalpollution_EnvironmentalEvaluationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environmentalpollution_EnvironmentalEvaluationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environmentalpollution_EnvironmentalEvaluationReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environmentalpollution_EnvironmentalEvaluationReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environmentalpollution_DecideLocationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environmentalpollution_DecideLocationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_environmentalpollution_DecideLocationReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_environmentalpollution_DecideLocationReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034EnvironmentalPollution.proto\022\026environm" +
      "entalpollution\"E\n\036EnvironmentalEvaluatio" +
      "nRequest\022#\n\033EnvironmentalPollutionLevel\030" +
      "\001 \001(\t\"-\n\034EnvironmentalEvaluationReply\022\r\n" +
      "\005Grade\030\001 \001(\t\")\n\025DecideLocationRequest\022\020\n" +
      "\010Location\030\001 \001(\t\"$\n\023DecideLocationReply\022\r" +
      "\n\005Grade\030\001 \001(\t2\232\002\n\026EnvironmentalPollution" +
      "\022\213\001\n\027EnvironmentalEvaluation\0226.environme" +
      "ntalpollution.EnvironmentalEvaluationReq" +
      "uest\0324.environmentalpollution.Environmen" +
      "talEvaluationReply\"\000(\001\022r\n\016DecideLocation" +
      "\022-.environmentalpollution.DecideLocation" +
      "Request\032+.environmentalpollution.DecideL" +
      "ocationReply\"\000(\0010\001BE\n\036service.environmen" +
      "talpollutionB!EnvironmentalPollutionServ" +
      "iceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_environmentalpollution_EnvironmentalEvaluationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_environmentalpollution_EnvironmentalEvaluationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environmentalpollution_EnvironmentalEvaluationRequest_descriptor,
        new java.lang.String[] { "EnvironmentalPollutionLevel", });
    internal_static_environmentalpollution_EnvironmentalEvaluationReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_environmentalpollution_EnvironmentalEvaluationReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environmentalpollution_EnvironmentalEvaluationReply_descriptor,
        new java.lang.String[] { "Grade", });
    internal_static_environmentalpollution_DecideLocationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_environmentalpollution_DecideLocationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environmentalpollution_DecideLocationRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_environmentalpollution_DecideLocationReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_environmentalpollution_DecideLocationReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_environmentalpollution_DecideLocationReply_descriptor,
        new java.lang.String[] { "Grade", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
